name: Validate Build Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Grant execute permission
        run: chmod +x mvnw

      - name: Build project
        run: ./mvnw clean package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: finova-jar
          path: target/*.jar